version: '3'

services:
  task1:
    image: run-client-image
    ports:
      - "5000:5000" # Expose port 8000 to the host machine
    environment:
      - FLASK_ENV=production
    working_dir: /client
    command: python __init__.py # Start the task1 process

  task2:
    image: run-sever-image
    ports:
      - "5001:5001" # Expose port 8001 to the host machine
    environment:
      - FLASK_ENV=production
    working_dir: /server
    command: python __init__.py  # Start the task2 process

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Expose port 80 to the host machine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount the nginx.conf file from your local machine
    depends_on:
      - task1
      - task2 # Wait for task1 and task2 to start before starting the nginx