# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFullIntegrationTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_fullIntegrationTest(self):
<<<<<<< HEAD
    self.driver.get("https://team-tbd-project-production.herokuapp.com/login")
=======
    self.driver.get("https://team-tbd-project-staging.herokuapp.com/login")
>>>>>>> 97298bf7771bdebffab79d33fe1bd21c41abbb50
    self.driver.set_window_size(1222, 816)
    self.driver.find_element(By.ID, "email").send_keys("test@tbd.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("test123")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "create-event-btn").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("My New Event")
    self.driver.find_element(By.ID, "start-date").send_keys("0002-05-04")
    self.driver.find_element(By.ID, "start-date").send_keys("0020-05-04")
    self.driver.find_element(By.ID, "start-date").send_keys("0202-05-04")
    self.driver.find_element(By.ID, "start-date").send_keys("2023-05-04")
    self.driver.find_element(By.ID, "start-time").click()
    self.driver.find_element(By.ID, "start-time").send_keys("09:00")
    self.driver.find_element(By.ID, "end-date").click()
    self.driver.find_element(By.ID, "end-date").send_keys("0002-05-04")
    self.driver.find_element(By.ID, "end-date").send_keys("0020-05-04")
    self.driver.find_element(By.ID, "end-date").send_keys("0202-05-04")
    self.driver.find_element(By.ID, "end-date").send_keys("2023-05-04")
    self.driver.find_element(By.ID, "end-time").click()
    self.driver.find_element(By.ID, "end-time").send_keys("10:00")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(11)").click()
    self.driver.find_element(By.ID, "toggle-switch").click()
    self.driver.find_element(By.LINK_TEXT, "+10 more").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fc-allow-mouse-resize .fc-title").click()
    assert self.driver.switch_to.alert.text == "Are you sure you want to delete \"My New Event\"?"
    self.driver.switch_to.alert.accept()
    assert self.driver.switch_to.alert.text == "Successfully deleted event"
    self.driver.find_element(By.ID, "toggle-switch").click()
    self.driver.find_element(By.LINK_TEXT, "Log Out").click()
  
